# Change these first
owner: tienthanh2509 # Your GitHub organization or username, where this repository lives
repo: pt-infra-status # The name of this repository

sites:
  - name: TDMU Elearning
    url: https://elearning.tdmu.edu.vn
  - name: TDMU Elearning SSO
    url: https://sso.tdmu.edu.vn
  - name: TDMU Elearning Chat
    url: https://chat.tdmu.edu.vn
  - name: TDMU Elearning ePortfolio
    url: https://eportfolio.tdmu.edu.vn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pt-infra.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "---"
  introMessage: ----
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
